// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cKTN0bAaxhlErQtIhSWxz1nBWmNspkU',
    appId: '1:433420738342:web:eb9742f1d976550d9eebe7',
    messagingSenderId: '433420738342',
    projectId: 'kedaireka-ugm',
    authDomain: 'kedaireka-ugm.firebaseapp.com',
    storageBucket: 'kedaireka-ugm.firebasestorage.app',
    measurementId: 'G-WKTBWKMLHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0waVWsi8v7GKK7311b0JScJg-wwd3nr8',
    appId: '1:433420738342:android:f740cfd4a650484c9eebe7',
    messagingSenderId: '433420738342',
    projectId: 'kedaireka-ugm',
    storageBucket: 'kedaireka-ugm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDTXl1wD1gcEA985pupQJIesGWMi6v-Uw',
    appId: '1:433420738342:ios:f05e014f90469c809eebe7',
    messagingSenderId: '433420738342',
    projectId: 'kedaireka-ugm',
    storageBucket: 'kedaireka-ugm.firebasestorage.app',
    iosBundleId: 'com.example.kedaireka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDTXl1wD1gcEA985pupQJIesGWMi6v-Uw',
    appId: '1:433420738342:ios:f05e014f90469c809eebe7',
    messagingSenderId: '433420738342',
    projectId: 'kedaireka-ugm',
    storageBucket: 'kedaireka-ugm.firebasestorage.app',
    iosBundleId: 'com.example.kedaireka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3cKTN0bAaxhlErQtIhSWxz1nBWmNspkU',
    appId: '1:433420738342:web:8c2beb33ce7f40609eebe7',
    messagingSenderId: '433420738342',
    projectId: 'kedaireka-ugm',
    authDomain: 'kedaireka-ugm.firebaseapp.com',
    storageBucket: 'kedaireka-ugm.firebasestorage.app',
    measurementId: 'G-SG1N54FKPT',
  );
}
